kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: iaas-request
  name: deployment-access
rules:
- apiGroups: ["extensions", "apps"] # "" indicates the core API group
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
