apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: test-music
  namespace: demo-authz
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: web
        tier: frontend
    spec:
      containers:
      - name: web
        image: datianshi/spring-music-new
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: in-memory
