kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: iaas-request
  name: pod-reader
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
